# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 03:25
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_tournament'),
    ]

    operations = [
		migrations.RunPython(lambda self, orm: call_command('createcachetable', 'cache'), migrations.RunPython.noop),
		migrations.RunSQL(migrations.RunSQL.noop, "DROP TABLE cache;")
    ]
